// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xypyycucutcbmjbmekvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5cHl5Y3VjdXRjYm1qYm1la3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDU1MTksImV4cCI6MjA2NDA4MTUxOX0.6OX-5J-pI4WU6dsW5j4en4B-l-A-4Ue6LHYChdm6FJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);