// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zidyrstcugsenimliwhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZHlyc3RjdWdzZW5pbWxpd2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDQ0NTksImV4cCI6MjA2NzkyMDQ1OX0.MczK1JPH4hlQNoIYdeX9TavnGhyIRFq09-fIs7CsGbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});